//! Specification 0008 deterministic manifested-bundle processing core.
use std::collections::{BTreeMap,BTreeSet};
use crate::{cbor::{self,Value},error::OlpError,json::Json,proof_identity,record,sha256,util::{hex_decode,hex_encode,is_absolute_uri}};

const DOMAIN:&str="OLP-EVIDENCE-BUNDLE-MANIFEST";
const PROFILES:[&str;2]=["portable","selfContainedVerification"];

#[derive(Clone,Debug,PartialEq,Eq,PartialOrd,Ord)]
struct EvidenceRef{kind:i64,digest:[u8;32]}
impl EvidenceRef{
 fn parse(v:&Json)->Result<Self,OlpError>{let a=v.as_array().map_err(|_|OlpError::malformed("EVIDENCE_REFERENCE_MALFORMED","EvidenceRefV1 must be array"))?;if a.len()!=2{return Err(OlpError::malformed("EVIDENCE_REFERENCE_MALFORMED","EvidenceRefV1 must contain two elements"));}let kind=a[0].as_i64().map_err(|_|OlpError::malformed("EVIDENCE_REFERENCE_MALFORMED","kind must be integer"))?;if kind!=0&&kind!=1{return Err(OlpError::malformed("EVIDENCE_REFERENCE_MALFORMED","unsupported evidence kind"));}let digest=parse_bytes(&a[1])?;let digest:[u8;32]=digest.try_into().map_err(|_|OlpError::malformed("EVIDENCE_REFERENCE_MALFORMED","digest must contain 32 octets"))?;Ok(Self{kind,digest})}
 fn canonical(&self)->Result<Vec<u8>,OlpError>{cbor::encode(&Value::Array(vec![Value::Int(self.kind as i128),Value::Bytes(self.digest.to_vec())])).map_err(|e|OlpError::malformed("EVIDENCE_REFERENCE_MALFORMED",e))}
 fn json(&self)->Json{let mut m=Json::object();m.insert("kind".into(),Json::Int(self.kind as i128));m.insert("identity_digest_hex".into(),Json::String(hex_encode(&self.digest)));Json::Object(m)}
}

#[derive(Clone,Debug)]
struct ResourceRef{resource_id:Option<String>,media_type:String,algorithm:i64,digest:[u8;32]}
impl ResourceRef{
 fn parse(v:&Json)->Result<Self,OlpError>{let a=v.as_array().map_err(|_|OlpError::malformed("MALFORMED_RESOURCE_REF","ResourceRefV1 must be array"))?;if a.len()!=4{return Err(OlpError::malformed("MALFORMED_RESOURCE_REF","ResourceRefV1 must contain four elements"));}let resource_id=match &a[0]{Json::Null=>None,Json::String(s)=>{if !is_absolute_uri(s){return Err(OlpError::malformed("MALFORMED_RESOURCE_REF","resource id must be absolute URI"));}Some(s.clone())},_=>return Err(OlpError::malformed("MALFORMED_RESOURCE_REF","resource id must be URI or null"))};let media_type=a[1].as_str().map_err(|_|OlpError::malformed("MALFORMED_RESOURCE_REF","media type must be text"))?.to_string();if !valid_media_type(&media_type){return Err(OlpError::malformed("MALFORMED_RESOURCE_REF","invalid media type"));}let algorithm=a[2].as_i64().map_err(|_|OlpError::malformed("MALFORMED_RESOURCE_REF","hash algorithm must be integer"))?;if algorithm!=-16{return Err(OlpError::unsupported("UNSUPPORTED_RESOURCE_HASH_ALGORITHM","unsupported resource hash algorithm"));}let d=parse_bytes(&a[3])?;let digest:[u8;32]=d.try_into().map_err(|_|OlpError::malformed("MALFORMED_RESOURCE_REF","digest must contain 32 octets"))?;Ok(Self{resource_id,media_type,algorithm,digest})}
 fn canonical(&self)->Result<Vec<u8>,OlpError>{cbor::encode(&Value::Array(vec![self.resource_id.as_ref().map(|s|Value::Text(s.clone())).unwrap_or(Value::Null),Value::Text(self.media_type.clone()),Value::Int(self.algorithm as i128),Value::Bytes(self.digest.to_vec())])).map_err(|e|OlpError::malformed("MALFORMED_RESOURCE_REF",e))}
 fn json(&self)->Json{let mut m=Json::object();m.insert("resource_id".into(),self.resource_id.as_ref().map(|s|Json::String(s.clone())).unwrap_or(Json::Null));m.insert("media_type".into(),Json::String(self.media_type.clone()));m.insert("hash_algorithm".into(),Json::Int(self.algorithm as i128));m.insert("digest_hex".into(),Json::String(hex_encode(&self.digest)));Json::Object(m)}
}
fn valid_media_type(s:&str)->bool{let mut it=s.split('/');let a=it.next().unwrap_or("");let b=it.next().unwrap_or("");if a.is_empty()||b.is_empty()||it.next().is_some(){return false;}fn ok(x:&str)->bool{x.bytes().all(|c|c.is_ascii_lowercase()||c.is_ascii_digit()||b"!#$&^_.+-".contains(&c))}ok(a)&&ok(b)}
fn parse_bytes(v:&Json)->Result<Vec<u8>,OlpError>{match v{Json::Object(m) if m.len()==1&&m.contains_key("$bytes")=>hex_decode(m.get("$bytes").unwrap().as_str().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?).map_err(|e|OlpError::malformed("MALFORMED_INPUT",e)),_=>Err(OlpError::malformed("MALFORMED_INPUT","expected $bytes wrapper"))}}
fn ref_json(kind:i64,digest:[u8;32])->Json{EvidenceRef{kind,digest}.json()}

pub fn process_bundle_operation(input:&Json)->Result<Json,OlpError>{
 let manifest=input.get("manifest_record").map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?;
 let bundle_id=record::identity_digest(manifest)?;
 let content=manifest.as_object().map_err(|e|OlpError::malformed("MALFORMED_BUNDLE_MANIFEST",e))?.get("content").ok_or_else(||OlpError::malformed("MALFORMED_BUNDLE_MANIFEST","missing content"))?;
 let a=content.as_array().map_err(|_|OlpError::malformed("MALFORMED_BUNDLE_MANIFEST","manifest content must be array"))?;if a.len()!=9{return Err(OlpError::malformed("MALFORMED_BUNDLE_MANIFEST","BundleManifestStatementV1 must contain nine elements"));}
 if a[0].as_str().map_err(|_|OlpError::malformed("MALFORMED_BUNDLE_MANIFEST","invalid discriminator"))?!=DOMAIN{return Err(OlpError::malformed("MALFORMED_BUNDLE_MANIFEST","invalid discriminator"));}
 let version=a[1].as_i64().map_err(|_|OlpError::malformed("MALFORMED_BUNDLE_MANIFEST","version must be integer"))?;if version!=1{return Err(OlpError::unsupported("UNSUPPORTED_BUNDLE_MANIFEST_VERSION","unsupported bundle version"));}
 let profile=a[2].as_str().map_err(|_|OlpError::malformed("MALFORMED_BUNDLE_MANIFEST","profile must be text"))?;if !PROFILES.contains(&profile){if is_absolute_uri(profile){return Err(OlpError::unsupported("UNSUPPORTED_BUNDLE_PROFILE","unsupported bundle profile"));}return Err(OlpError::malformed("MALFORMED_BUNDLE_MANIFEST","extension profile must be absolute URI"));}
 let roots=parse_ref_array(&a[3],"ROOTS")?;let inventory=parse_ref_array(&a[4],"INVENTORY")?;
 let invset:BTreeSet<EvidenceRef>=inventory.iter().cloned().collect();if roots.iter().any(|r|!invset.contains(r)){return Err(OlpError::malformed("BUNDLE_ROOT_NOT_IN_INVENTORY","root absent from inventory"));}
 let resources=parse_resource_array(&a[5])?;
 let metadata=a[6].as_object().map_err(|_|OlpError::malformed("MALFORMED_BUNDLE_METADATA","metadata must be map"))?;if !metadata.is_empty(){return Err(OlpError::malformed("MALFORMED_BUNDLE_METADATA","integer-keyed metadata must use adapter $map encoding; nonempty ordinary object is unsupported in core vectors"));}
 let extensions=a[7].as_object().map_err(|_|OlpError::malformed("MALFORMED_BUNDLE_EXTENSION","extensions must be map"))?;for k in extensions.keys(){if !is_absolute_uri(k){return Err(OlpError::malformed("MALFORMED_BUNDLE_EXTENSION","extension key must be absolute URI"));}}
 let critical=a[8].as_array().map_err(|_|OlpError::malformed("MALFORMED_BUNDLE_EXTENSION","critical must be array"))?;let understood: BTreeSet<String>=match input.get_opt("understood_critical_extensions").map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?{None=>BTreeSet::new(),Some(Json::Array(v))=>v.iter().map(|x|x.as_str().map(str::to_string).map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))).collect::<Result<_,_>>()?,Some(_)=>return Err(OlpError::malformed("MALFORMED_INPUT","understood_critical_extensions must be array"))};let mut prev:Option<&[u8]>=None;let mut seen=BTreeSet::new();for c in critical{let s=c.as_str().map_err(|_|OlpError::malformed("MALFORMED_BUNDLE_EXTENSION","critical member must be text"))?;if !is_absolute_uri(s)||!extensions.contains_key(s)||!seen.insert(s.to_string()){return Err(OlpError::malformed("MALFORMED_BUNDLE_EXTENSION","invalid critical extension"));}if let Some(p)=prev{if p>=s.as_bytes(){return Err(OlpError::malformed("MALFORMED_BUNDLE_EXTENSION","critical extensions must be sorted"));}}prev=Some(s.as_bytes());if !understood.contains(s){return Err(OlpError::unsupported("UNSUPPORTED_CRITICAL_BUNDLE_EXTENSION","unsupported critical bundle extension"));}}

 let mut supplied:BTreeMap<EvidenceRef,Json>=BTreeMap::new();let mut duplicate=Vec::new();
 if let Some(Json::Array(rs))=input.get_opt("records").map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?{for r in rs{let d=record::identity_digest(r)?;let er=EvidenceRef{kind:0,digest:d};if supplied.insert(er.clone(),r.clone()).is_some(){duplicate.push(hex_encode(&d));}}}
 else if input.get_opt("records").map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?.is_some(){return Err(OlpError::malformed("MALFORMED_INPUT","records must be array"));}
 if let Some(Json::Array(ps))=input.get_opt("proofs").map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?{for p in ps{let d=proof_identity::proof_identity_digest_for(p)?;let er=EvidenceRef{kind:1,digest:d};if supplied.insert(er.clone(),p.clone()).is_some(){duplicate.push(hex_encode(&d));}}}
 let supplied_set:BTreeSet<EvidenceRef>=supplied.keys().cloned().collect();let missing:Vec<EvidenceRef>=invset.difference(&supplied_set).cloned().collect();let unexpected:Vec<EvidenceRef>=supplied_set.difference(&invset).cloned().collect();

 let expected_resources:BTreeMap<Vec<u8>,ResourceRef>=resources.iter().map(|r|Ok((r.canonical()?,r.clone()))).collect::<Result<_,OlpError>>()?;let mut seen_resources:BTreeMap<Vec<u8>,ResourceRef>=BTreeMap::new();let mut resource_errors=Vec::new();
 if let Some(Json::Array(items))=input.get_opt("resources").map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?{for item in items{let o=item.as_object().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?;let rr=o.get("resource_ref").ok_or_else(||OlpError::malformed("MALFORMED_INPUT","missing resource_ref"))?.as_object().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?;let resource_id=match rr.get("resource_id"){None|Some(Json::Null)=>None,Some(Json::String(s))=>{if !is_absolute_uri(s){return Err(OlpError::malformed("MALFORMED_RESOURCE_REF","invalid resource id"));}Some(s.clone())},Some(_)=>return Err(OlpError::malformed("MALFORMED_RESOURCE_REF","invalid resource id"))};let media=rr.get("media_type").ok_or_else(||OlpError::malformed("MALFORMED_RESOURCE_REF","missing media type"))?.as_str().map_err(|e|OlpError::malformed("MALFORMED_RESOURCE_REF",e))?.to_string();if !valid_media_type(&media){return Err(OlpError::malformed("MALFORMED_RESOURCE_REF","invalid media type"));}let alg=rr.get("hash_algorithm").map(|v|v.as_i64()).transpose().map_err(|e|OlpError::malformed("MALFORMED_RESOURCE_REF",e))?.unwrap_or(-16);if alg!=-16{return Err(OlpError::unsupported("UNSUPPORTED_RESOURCE_HASH_ALGORITHM","unsupported resource hash algorithm"));}let dh=rr.get("digest_hex").ok_or_else(||OlpError::malformed("MALFORMED_RESOURCE_REF","missing digest"))?.as_str().map_err(|e|OlpError::malformed("MALFORMED_RESOURCE_REF",e))?;let dv=hex_decode(dh).map_err(|e|OlpError::malformed("MALFORMED_RESOURCE_REF",e))?;let digest:[u8;32]=dv.try_into().map_err(|_|OlpError::malformed("MALFORMED_RESOURCE_REF","digest must contain 32 octets"))?;let r=ResourceRef{resource_id,media_type:media,algorithm:alg,digest};let content=hex_decode(o.get("content_hex").ok_or_else(||OlpError::malformed("MALFORMED_INPUT","missing content_hex"))?.as_str().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?).map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?;if sha256::digest(&content)!=r.digest{let mut e=Json::object();e.insert("reason".into(),Json::String("RESOURCE_DIGEST_MISMATCH".into()));e.insert("resource_digest_hex".into(),Json::String(hex_encode(&r.digest)));resource_errors.push(Json::Object(e));}let key=r.canonical()?;if seen_resources.insert(key.clone(),r.clone()).is_some(){let mut e=Json::object();e.insert("reason".into(),Json::String("DUPLICATE_PACKAGED_RESOURCE".into()));e.insert("resource_digest_hex".into(),Json::String(hex_encode(&r.digest)));resource_errors.push(Json::Object(e));}}}
 let missing_resources:Vec<ResourceRef>=expected_resources.iter().filter(|(k,_)|!seen_resources.contains_key(*k)).map(|(_,v)|v.clone()).collect();let unexpected_resources:Vec<ResourceRef>=seen_resources.iter().filter(|(k,_)|!expected_resources.contains_key(*k)).map(|(_,v)|v.clone()).collect();
 let status=if !resource_errors.is_empty(){"INVALID"}else if !missing.is_empty()||!unexpected.is_empty()||!missing_resources.is_empty()||!unexpected_resources.is_empty()||!duplicate.is_empty(){"PARTIAL"}else{"VALID"};
 let mut out=Json::object();out.insert("status".into(),Json::String(status.into()));out.insert("bundle_id_hex".into(),Json::String(hex_encode(&bundle_id)));out.insert("profile".into(),Json::String(profile.into()));out.insert("network_fallback_allowed".into(),Json::Bool(profile!="selfContainedVerification"));out.insert("root_results".into(),Json::Array(roots.iter().map(|r|{let mut x=Json::object();x.insert("ref".into(),r.json());x.insert("present".into(),Json::Bool(supplied_set.contains(r)));Json::Object(x)}).collect()));out.insert("missing_items".into(),Json::Array(missing.iter().map(|r|r.json()).collect()));out.insert("unexpected_items".into(),Json::Array(unexpected.iter().map(|r|r.json()).collect()));duplicate.sort();out.insert("duplicate_supplied_identity_hex".into(),Json::Array(duplicate.into_iter().map(Json::String).collect()));out.insert("missing_resources".into(),Json::Array(missing_resources.iter().map(|r|r.json()).collect()));out.insert("unexpected_resources".into(),Json::Array(unexpected_resources.iter().map(|r|r.json()).collect()));out.insert("resource_errors".into(),Json::Array(resource_errors));out.insert("closure_status".into(),Json::String(if status=="VALID"{"COMPLETE"}else{"INCOMPLETE"}.into()));Ok(Json::Object(out))
}

fn parse_ref_array(v:&Json,label:&str)->Result<Vec<EvidenceRef>,OlpError>{let a=v.as_array().map_err(|_|OlpError::malformed("MALFORMED_BUNDLE_MANIFEST",format!("{label} must be array")))?;let mut out=Vec::new();let mut canonical=Vec::new();let mut seen=BTreeSet::new();for x in a{let r=EvidenceRef::parse(x)?;let c=r.canonical()?;if !seen.insert(c.clone()){return Err(OlpError::malformed(&format!("DUPLICATE_BUNDLE_{label}"),"duplicate bundle reference"));}canonical.push(c);out.push(r);}let mut sorted=canonical.clone();sorted.sort();if canonical!=sorted{return Err(OlpError::malformed(&format!("NON_CANONICAL_BUNDLE_{label}_ORDER"),"bundle references are not canonically sorted"));}Ok(out)}
fn parse_resource_array(v:&Json)->Result<Vec<ResourceRef>,OlpError>{let a=v.as_array().map_err(|_|OlpError::malformed("MALFORMED_BUNDLE_MANIFEST","resource inventory must be array"))?;let mut out=Vec::new();let mut canonical=Vec::new();let mut seen=BTreeSet::new();for x in a{let r=ResourceRef::parse(x)?;let c=r.canonical()?;if !seen.insert(c.clone()){return Err(OlpError::malformed("DUPLICATE_BUNDLE_RESOURCE","duplicate resource inventory entry"));}canonical.push(c);out.push(r);}let mut sorted=canonical.clone();sorted.sort();if canonical!=sorted{return Err(OlpError::malformed("NON_CANONICAL_BUNDLE_RESOURCE_ORDER","resource inventory is not canonically sorted"));}Ok(out)}
