//! Specification 0004 proof construction and structured verification.
use std::collections::{BTreeMap,BTreeSet};
use crate::{cbor::{self,Value},error::OlpError,json::Json,openssl_ed25519,record,sha256,time,util::{hex_decode,hex_encode,is_absolute_uri,is_semantic_identifier}};

pub const SUITE:&str="eddsa-ed25519-v1";pub const HASH_SHA256:i64=-16;
const CORE_PURPOSES:[&str;4]=["assertion","acknowledgement","witness","authorization"];
const CORE_PROPS:[&str;14]=["type","version","cryptosuite","proofPurpose","verificationMethod","recordCommitment","proofValue","created","expires","domain","challenge","nonce","critical","extensions"];

#[derive(Clone,Debug)]pub struct Commitment{pub algorithm:i64,pub digest:Vec<u8>}
#[derive(Clone,Debug)]pub struct Proof{pub typ:String,pub version:i64,pub cryptosuite:String,pub purpose:String,pub method:String,pub commitment:Commitment,pub signature:Vec<u8>,pub created:Option<String>,pub expires:Option<String>,pub domain:Option<String>,pub challenge:Option<Vec<u8>>,pub nonce:Option<Vec<u8>>,pub critical:Vec<String>,pub extensions:BTreeMap<String,Json>}

fn metadata_value(p:&Proof)->Value{let mut rows=Vec::new();if let Some(v)=&p.created{rows.push((Value::Int(0),Value::Text(v.clone())))}if let Some(v)=&p.expires{rows.push((Value::Int(1),Value::Text(v.clone())))}if let Some(v)=&p.domain{rows.push((Value::Int(2),Value::Text(v.clone())))}if let Some(v)=&p.challenge{rows.push((Value::Int(3),Value::Bytes(v.clone())))}if let Some(v)=&p.nonce{rows.push((Value::Int(4),Value::Bytes(v.clone())))}Value::Map(rows)}
fn valid_proof_extension_value(v:&Json,depth:usize)->bool{
 if depth>cbor::MAX_DEPTH{return false;}
 match v{
  Json::Null|Json::Bool(_)|Json::String(_)=>true,
  Json::Int(n)=>*n>=-(1i128<<63)&&*n<=(1i128<<63)-1,
  Json::Array(a)=>a.len()<=cbor::MAX_COLLECTION_ITEMS&&a.iter().all(|x|valid_proof_extension_value(x,depth+1)),
  Json::Object(m) if m.len()==1&&m.contains_key("$bytes")=>m.get("$bytes").is_some_and(|x|x.as_str().ok().is_some_and(|h|hex_decode(h).is_ok())),
  Json::Object(m) if m.len()==1&&m.contains_key("$map")=>m.get("$map").is_some_and(|entries|entries.as_array().ok().is_some_and(|a|a.len()<=cbor::MAX_COLLECTION_ITEMS&&a.iter().all(|entry|entry.as_array().ok().is_some_and(|pair|pair.len()==2&&matches!(&pair[0],Json::String(_) | Json::Int(_))&&!matches!(&pair[0],Json::Bool(_))&&valid_proof_extension_value(&pair[1],depth+1))))),
  Json::Object(m)=>m.len()<=cbor::MAX_COLLECTION_ITEMS&&m.values().all(|x|valid_proof_extension_value(x,depth+1)),
 }
}
fn extensions_value(p:&Proof)->Result<Value,OlpError>{
 for v in p.extensions.values(){if !valid_proof_extension_value(v,0){return Err(OlpError::malformed("INVALID_EXTENSION_VALUE","extension value is outside the Proof Input v1 value model"));}}
 cbor::adapter_string_map(&p.extensions).map_err(|e|OlpError::malformed("INVALID_EXTENSION_VALUE",e))
}
pub fn proof_input(p:&Proof)->Result<Value,OlpError>{let mut critical=p.critical.clone();critical.sort_by(|a,b|a.as_bytes().cmp(b.as_bytes()));Ok(Value::Array(vec![Value::Text("OLP-PROOF".into()),Value::Int(1),Value::Text(p.cryptosuite.clone()),Value::Text(p.purpose.clone()),Value::Text(p.method.clone()),Value::Array(vec![Value::Int(p.commitment.algorithm as i128),Value::Bytes(p.commitment.digest.clone())]),metadata_value(p),extensions_value(p)?,Value::Array(critical.into_iter().map(Value::Text).collect())]))}
pub fn proof_input_bytes(p:&Proof)->Result<Vec<u8>,OlpError>{cbor::encode(&proof_input(p)?).map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))}

pub fn validate_structure(p:&Proof)->Result<(),OlpError>{
 if p.typ!="OLPProof"{return Err(OlpError::malformed("INVALID_CORE_PROPERTY","proof type must equal OLPProof"));}
 if p.version<0{return Err(OlpError::malformed("INVALID_CORE_PROPERTY","version must be non-negative"));}
 if !is_semantic_identifier(&p.cryptosuite)||!is_semantic_identifier(&p.purpose)||!is_absolute_uri(&p.method){return Err(OlpError::malformed("INVALID_CORE_PROPERTY","invalid proof identifier property"));}
 if p.commitment.digest.is_empty(){return Err(OlpError::malformed("INVALID_CORE_PROPERTY","record commitment digest must be non-empty"));}
 if let Some(v)=&p.created{if !time::valid(v){return Err(OlpError::malformed("INVALID_CORE_PROPERTY","created must be RFC3339"));}}
 if let Some(v)=&p.expires{if !time::valid(v){return Err(OlpError::malformed("INVALID_CORE_PROPERTY","expires must be RFC3339"));}}
 if let Some(v)=&p.domain{if v.is_empty(){return Err(OlpError::malformed("INVALID_CORE_PROPERTY","domain must be non-empty"));}}
 if let Some(v)=&p.challenge{if v.is_empty(){return Err(OlpError::malformed("INVALID_CORE_PROPERTY","challenge must be non-empty"));}}
 if let Some(v)=&p.nonce{if v.is_empty(){return Err(OlpError::malformed("INVALID_CORE_PROPERTY","nonce must be non-empty"));}}
 for(k,v)in &p.extensions{if !is_absolute_uri(k)||CORE_PROPS.contains(&k.as_str()){return Err(OlpError::malformed("INVALID_EXTENSION_NAME","invalid proof extension name"));}if !valid_proof_extension_value(v,0){return Err(OlpError::malformed("INVALID_EXTENSION_VALUE","extension value is outside the Proof Input v1 value model"));}cbor::from_adapter_json(v).map_err(|e|OlpError::malformed("INVALID_EXTENSION_VALUE",e))?;}
 let mut seen=BTreeSet::new();for c in &p.critical{if !seen.insert(c)||!is_absolute_uri(c)||!p.extensions.contains_key(c)||CORE_PROPS.contains(&c.as_str()){return Err(OlpError::malformed("INVALID_CRITICAL_DECLARATION","invalid critical extension declaration"));}}
 if p.version==1&&p.cryptosuite==SUITE&&p.signature.len()!=64{return Err(OlpError::malformed("INVALID_PROOF_VALUE_LENGTH","Ed25519 proofValue must be 64 octets"));}
 Ok(())
}

fn opt_str(o:&BTreeMap<String,Json>,key:&str)->Result<Option<String>,OlpError>{match o.get(key){None=>Ok(None),Some(Json::String(s))=>Ok(Some(s.clone())),Some(_)=>Err(OlpError::malformed("INVALID_CORE_PROPERTY",format!("{key} must be string")))}}
fn opt_hex(o:&BTreeMap<String,Json>,key:&str)->Result<Option<Vec<u8>>,OlpError>{match o.get(key){None=>Ok(None),Some(Json::String(s))=>Ok(Some(hex_decode(s).map_err(|e|OlpError::malformed("INVALID_CORE_PROPERTY",e))?)),Some(_)=>Err(OlpError::malformed("INVALID_CORE_PROPERTY",format!("{key} must be hex string")))}}
fn parse_extensions(o:&BTreeMap<String,Json>)->Result<BTreeMap<String,Json>,OlpError>{match o.get("extensions"){None=>Ok(BTreeMap::new()),Some(Json::Object(m))=>Ok(m.clone()),Some(_)=>Err(OlpError::malformed("INVALID_EXTENSION_VALUE","extensions must be map"))}}
fn parse_critical(o:&BTreeMap<String,Json>)->Result<Vec<String>,OlpError>{match o.get("critical"){None=>Ok(Vec::new()),Some(Json::Array(a))=>a.iter().map(|v|v.as_str().map(str::to_string).map_err(|e|OlpError::malformed("INVALID_CRITICAL_DECLARATION",e))).collect(),Some(_)=>Err(OlpError::malformed("INVALID_CRITICAL_DECLARATION","critical must be array"))}}

pub fn parse_proof(v:&Json)->Result<Proof,OlpError>{let o=v.as_object().map_err(|e|OlpError::malformed("MALFORMED_PROOF",e))?;let rc=o.get("recordCommitment").ok_or_else(||OlpError::malformed("INVALID_CORE_PROPERTY","missing recordCommitment"))?.as_object().map_err(|e|OlpError::malformed("INVALID_CORE_PROPERTY",e))?;let algorithm=rc.get("algorithm").ok_or_else(||OlpError::malformed("INVALID_CORE_PROPERTY","missing commitment algorithm"))?.as_i64().map_err(|e|OlpError::malformed("INVALID_CORE_PROPERTY",e))?;let digest_hex=rc.get("digest_hex").ok_or_else(||OlpError::malformed("INVALID_CORE_PROPERTY","missing commitment digest"))?.as_str().map_err(|e|OlpError::malformed("INVALID_CORE_PROPERTY",e))?;let signature_hex=o.get("proofValue_hex").ok_or_else(||OlpError::malformed("INVALID_CORE_PROPERTY","missing proofValue_hex"))?.as_str().map_err(|e|OlpError::malformed("INVALID_CORE_PROPERTY",e))?;Ok(Proof{typ:opt_str(o,"type")?.unwrap_or_else(||"OLPProof".into()),version:o.get("version").ok_or_else(||OlpError::malformed("INVALID_CORE_PROPERTY","missing version"))?.as_i64().map_err(|e|OlpError::malformed("INVALID_CORE_PROPERTY",e))?,cryptosuite:o.get("cryptosuite").ok_or_else(||OlpError::malformed("INVALID_CORE_PROPERTY","missing cryptosuite"))?.as_str().map_err(|e|OlpError::malformed("INVALID_CORE_PROPERTY",e))?.into(),purpose:o.get("proofPurpose").ok_or_else(||OlpError::malformed("INVALID_CORE_PROPERTY","missing proofPurpose"))?.as_str().map_err(|e|OlpError::malformed("INVALID_CORE_PROPERTY",e))?.into(),method:o.get("verificationMethod").ok_or_else(||OlpError::malformed("INVALID_CORE_PROPERTY","missing verificationMethod"))?.as_str().map_err(|e|OlpError::malformed("INVALID_CORE_PROPERTY",e))?.into(),commitment:Commitment{algorithm,digest:hex_decode(digest_hex).map_err(|e|OlpError::malformed("INVALID_CORE_PROPERTY",e))?},signature:hex_decode(signature_hex).map_err(|e|OlpError::malformed("INVALID_CORE_PROPERTY",e))?,created:opt_str(o,"created")?,expires:opt_str(o,"expires")?,domain:opt_str(o,"domain")?,challenge:opt_hex(o,"challenge_hex")?,nonce:opt_hex(o,"nonce_hex")?,critical:parse_critical(o)?,extensions:parse_extensions(o)?})}

pub fn proof_to_json(p:&Proof)->Json{let mut o=Json::object();o.insert("type".into(),Json::String(p.typ.clone()));o.insert("version".into(),Json::Int(p.version as i128));o.insert("cryptosuite".into(),Json::String(p.cryptosuite.clone()));o.insert("proofPurpose".into(),Json::String(p.purpose.clone()));o.insert("verificationMethod".into(),Json::String(p.method.clone()));let mut rc=Json::object();rc.insert("algorithm".into(),Json::Int(p.commitment.algorithm as i128));rc.insert("digest_hex".into(),Json::String(hex_encode(&p.commitment.digest)));o.insert("recordCommitment".into(),Json::Object(rc));o.insert("proofValue_hex".into(),Json::String(hex_encode(&p.signature)));o.insert("critical".into(),Json::Array(p.critical.iter().cloned().map(Json::String).collect()));o.insert("extensions".into(),Json::Object(p.extensions.clone()));if let Some(v)=&p.created{o.insert("created".into(),Json::String(v.clone()));}if let Some(v)=&p.expires{o.insert("expires".into(),Json::String(v.clone()));}if let Some(v)=&p.domain{o.insert("domain".into(),Json::String(v.clone()));}if let Some(v)=&p.challenge{o.insert("challenge_hex".into(),Json::String(hex_encode(v)));}if let Some(v)=&p.nonce{o.insert("nonce_hex".into(),Json::String(hex_encode(v)));}Json::Object(o)}

pub fn commitment(record_json:&Json,algorithm:i64)->Result<Commitment,OlpError>{if algorithm!=HASH_SHA256{return Err(OlpError::unsupported("UNSUPPORTED_COMMITMENT_ALGORITHM",format!("unsupported commitment algorithm {algorithm}")));}let bytes=record::identity_bytes(record_json)?;Ok(Commitment{algorithm,digest:sha256::digest(&bytes).to_vec()})}

pub fn encode_input_operation(payload:&Json)->Result<Json,OlpError>{let o=payload.as_object().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?;let rc=o.get("record_commitment").ok_or_else(||OlpError::malformed("MALFORMED_INPUT","missing record_commitment"))?.as_object().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?;let mut p=Proof{typ:"OLPProof".into(),version:1,cryptosuite:o.get("cryptosuite").ok_or_else(||OlpError::malformed("MALFORMED_INPUT","missing cryptosuite"))?.as_str().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?.into(),purpose:o.get("proof_purpose").ok_or_else(||OlpError::malformed("MALFORMED_INPUT","missing proof_purpose"))?.as_str().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?.into(),method:o.get("verification_method").ok_or_else(||OlpError::malformed("MALFORMED_INPUT","missing verification_method"))?.as_str().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?.into(),commitment:Commitment{algorithm:rc.get("algorithm").ok_or_else(||OlpError::malformed("MALFORMED_INPUT","missing algorithm"))?.as_i64().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?,digest:hex_decode(rc.get("digest_hex").ok_or_else(||OlpError::malformed("MALFORMED_INPUT","missing digest_hex"))?.as_str().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?).map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?},signature:vec![0;64],created:opt_str(o,"created")?,expires:opt_str(o,"expires")?,domain:opt_str(o,"domain")?,challenge:opt_hex(o,"challenge_hex")?,nonce:opt_hex(o,"nonce_hex")?,critical:parse_critical(o)?,extensions:parse_extensions(o)?};p.critical.sort_by(|a,b|a.as_bytes().cmp(b.as_bytes()));validate_structure(&p)?;let bytes=proof_input_bytes(&p)?;let mut r=Json::object();r.insert("proof_input_hex".into(),Json::String(hex_encode(&bytes)));r.insert("proof_input_length".into(),Json::Int(bytes.len()as i128));Ok(Json::Object(r))}

pub fn create_operation(payload:&Json)->Result<Json,OlpError>{let o=payload.as_object().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?;let record_json=o.get("record").ok_or_else(||OlpError::malformed("MALFORMED_INPUT","missing record"))?;record::identity_preimage(record_json)?;let cfg=o.get("proof_configuration").ok_or_else(||OlpError::malformed("MALFORMED_INPUT","missing proof_configuration"))?.as_object().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?;let suite=opt_str(cfg,"cryptosuite")?.unwrap_or_else(||SUITE.into());if suite!=SUITE{return Err(OlpError::unsupported("UNSUPPORTED_CRYPTOSUITE",format!("unsupported cryptosuite {suite}")));}let alg=match cfg.get("commitment_algorithm"){None=>HASH_SHA256,Some(v)=>v.as_i64().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?};let comm=commitment(record_json,alg)?;let seed=hex_decode(o.get("private_seed_hex").ok_or_else(||OlpError::malformed("MALFORMED_INPUT","missing private seed"))?.as_str().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?).map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?;if seed.len()!=32{return Err(OlpError::malformed("MALFORMED_INPUT","Ed25519 private seed must contain 32 octets"));}let mut p=Proof{typ:"OLPProof".into(),version:1,cryptosuite:suite,purpose:cfg.get("proof_purpose").ok_or_else(||OlpError::malformed("MALFORMED_INPUT","missing proof_purpose"))?.as_str().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?.into(),method:cfg.get("verification_method").ok_or_else(||OlpError::malformed("MALFORMED_INPUT","missing verification_method"))?.as_str().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?.into(),commitment:comm,signature:vec![0;64],created:opt_str(cfg,"created")?,expires:opt_str(cfg,"expires")?,domain:opt_str(cfg,"domain")?,challenge:opt_hex(cfg,"challenge_hex")?,nonce:opt_hex(cfg,"nonce_hex")?,critical:parse_critical(cfg)?,extensions:parse_extensions(cfg)?};validate_structure(&p)?;let bytes=proof_input_bytes(&p)?;p.signature=openssl_ed25519::sign(&seed,&bytes).map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?.to_vec();let mut r=Json::object();r.insert("proof".into(),proof_to_json(&p));r.insert("proof_input_hex".into(),Json::String(hex_encode(&bytes)));Ok(Json::Object(r))}

#[derive(Clone)]struct ResultBuilder{fields:BTreeMap<String,Json>,errors:Vec<String>,warnings:Vec<String>}
impl ResultBuilder{fn new()->Self{let mut f=BTreeMap::new();for k in ["conformance","record_binding","version_support","cryptosuite_support","commitment_algorithm_support","critical_extension_status","verification_method_resolution","verification_method_compatibility","cryptographic_validity","purpose_status","domain_status","challenge_status","temporal_status","verification_method_status"]{f.insert(k.into(),Json::String("NOT_EVALUATED".into()));}f.insert("resolution_provenance".into(),Json::Null);Self{fields:f,errors:Vec::new(),warnings:Vec::new()}}fn set(&mut self,k:&str,v:&str){self.fields.insert(k.into(),Json::String(v.into()));}fn err(&mut self,c:&str){if !self.errors.contains(&c.to_string()){self.errors.push(c.into());}}fn warn(&mut self,c:&str){if !self.warnings.contains(&c.to_string()){self.warnings.push(c.into());}}fn finish(mut self)->Json{self.fields.insert("error_codes".into(),Json::Array(self.errors.iter().cloned().map(Json::String).collect()));self.fields.insert("warning_codes".into(),Json::Array(self.warnings.iter().cloned().map(Json::String).collect()));self.fields.insert("errors".into(),Json::Array(self.errors.into_iter().map(|c|{let mut m=Json::object();m.insert("code".into(),Json::String(c));m.insert("message".into(),Json::String("see reason code".into()));Json::Object(m)}).collect()));self.fields.insert("warnings".into(),Json::Array(self.warnings.into_iter().map(|c|{let mut m=Json::object();m.insert("code".into(),Json::String(c));m.insert("message".into(),Json::String("see reason code".into()));Json::Object(m)}).collect()));Json::Object(self.fields)}}

fn strset(v:Option<&Json>,defaults:&[&str])->Result<Option<BTreeSet<String>>,OlpError>{match v{None=>Ok(Some(defaults.iter().map(|s|s.to_string()).collect())),Some(Json::Null)=>Ok(None),Some(Json::Array(a))=>Ok(Some(a.iter().map(|x|x.as_str().map(str::to_string).map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))).collect::<Result<BTreeSet<_>,_>>()?)),Some(_)=>Err(OlpError::malformed("MALFORMED_INPUT","policy set must be array or null"))}}
fn intset(v:Option<&Json>,defaults:&[i64])->Result<Option<BTreeSet<i64>>,OlpError>{match v{None=>Ok(Some(defaults.iter().copied().collect())),Some(Json::Null)=>Ok(None),Some(Json::Array(a))=>Ok(Some(a.iter().map(|x|x.as_i64().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))).collect::<Result<BTreeSet<_>,_>>()?)),Some(_)=>Err(OlpError::malformed("MALFORMED_INPUT","policy integer set must be array or null"))}}

pub fn verify_operation(payload:&Json)->Result<Json,OlpError>{let o=payload.as_object().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?;let record_json=o.get("record").ok_or_else(||OlpError::malformed("MALFORMED_INPUT","missing record"))?;let p=parse_proof(o.get("proof").ok_or_else(||OlpError::malformed("MALFORMED_INPUT","missing proof"))?)?;let context=match o.get("context"){None=>BTreeMap::new(),Some(Json::Object(m))=>m.clone(),Some(_)=>return Err(OlpError::malformed("MALFORMED_INPUT","context must be object"))};let policy=match o.get("policy"){None=>BTreeMap::new(),Some(Json::Object(m))=>m.clone(),Some(_)=>return Err(OlpError::malformed("MALFORMED_INPUT","policy must be object"))};let understood_ext=strset(policy.get("understood_extensions"),&[])?.unwrap_or_default();let understood_purpose=strset(policy.get("understood_proof_purposes"),&CORE_PURPOSES)?.unwrap_or_default();let allowed_algs=intset(policy.get("allowed_commitment_algorithms"),&[HASH_SHA256])?;let allowed_suites=strset(policy.get("allowed_cryptosuites"),&[SUITE])?;let mut r=ResultBuilder::new();
 if let Err(e)=validate_structure(&p){r.set("conformance","NONCONFORMING");r.err(&e.reason);return Ok(r.finish());}r.set("conformance","CONFORMING");
 if p.version!=1{r.set("version_support","UNSUPPORTED");r.err("UNSUPPORTED_VERSION");return Ok(r.finish());}r.set("version_support","SUPPORTED");
 let suite_ok=p.cryptosuite==SUITE;if !suite_ok{r.set("cryptosuite_support","UNSUPPORTED");r.err("UNSUPPORTED_CRYPTOSUITE")}else if allowed_suites.as_ref().is_some_and(|s|!s.contains(&p.cryptosuite)){r.set("cryptosuite_support","REJECTED_BY_POLICY");r.err("CRYPTOSUITE_REJECTED_BY_POLICY")}else{r.set("cryptosuite_support","SUPPORTED")}
 let unknown_critical:Vec<_>=p.critical.iter().filter(|x|!understood_ext.contains(*x)).collect();if unknown_critical.is_empty(){r.set("critical_extension_status","UNDERSTOOD")}else{r.set("critical_extension_status","UNSUPPORTED");r.err("UNSUPPORTED_CRITICAL_EXTENSION")}
 for k in p.extensions.keys(){if !understood_ext.contains(k)&&!p.critical.contains(k){r.warn("UNKNOWN_NONCRITICAL_EXTENSION");}}
 if p.commitment.algorithm!=HASH_SHA256{r.set("commitment_algorithm_support","UNSUPPORTED");r.err("UNSUPPORTED_COMMITMENT_ALGORITHM")}else{if allowed_algs.as_ref().is_some_and(|s|!s.contains(&p.commitment.algorithm)){r.set("commitment_algorithm_support","REJECTED_BY_POLICY");r.err("COMMITMENT_ALGORITHM_REJECTED_BY_POLICY")}else{r.set("commitment_algorithm_support","SUPPORTED")}let actual=sha256::digest(&record::identity_bytes(record_json)?);if actual.as_slice()==p.commitment.digest.as_slice(){r.set("record_binding","VALID")}else{r.set("record_binding","INVALID");r.err("RECORD_COMMITMENT_MISMATCH")}}
 let resolved=o.get("resolved_method");let mut pubkey:Option<Vec<u8>>=None;if resolved.is_none()||matches!(resolved,Some(Json::Null)){r.set("verification_method_resolution","UNAVAILABLE");r.err("VERIFICATION_METHOD_UNAVAILABLE")}else{let m=resolved.unwrap().as_object().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?;r.set("verification_method_resolution","RESOLVED");let provenance=opt_str(m,"provenance")?.unwrap_or_else(||"supplied".into());r.fields.insert("resolution_provenance".into(),Json::String(provenance));let id=m.get("identifier").ok_or_else(||OlpError::malformed("MALFORMED_INPUT","resolved method missing identifier"))?.as_str().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?;let key_type=m.get("key_type").ok_or_else(||OlpError::malformed("MALFORMED_INPUT","resolved method missing key_type"))?.as_str().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?;let pk=hex_decode(m.get("public_key_hex").ok_or_else(||OlpError::malformed("MALFORMED_INPUT","resolved method missing public key"))?.as_str().map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?).map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?;if id!=p.method{r.set("verification_method_compatibility","MISMATCH");r.err("VERIFICATION_METHOD_MISMATCH")}else if suite_ok&&key_type!="Ed25519"{r.set("verification_method_compatibility","INCOMPATIBLE");r.err("VERIFICATION_METHOD_INCOMPATIBLE")}else if suite_ok&&pk.len()!=32{r.set("verification_method_compatibility","INCOMPATIBLE");r.err("INVALID_PUBLIC_KEY_LENGTH")}else{r.set("verification_method_compatibility","COMPATIBLE");pubkey=Some(pk)}}
 let prereq=suite_ok&&p.commitment.algorithm==HASH_SHA256&&matches!(r.fields.get("record_binding"),Some(Json::String(s)) if s=="VALID")&&matches!(r.fields.get("verification_method_compatibility"),Some(Json::String(s)) if s=="COMPATIBLE");if prereq{let msg=proof_input_bytes(&p)?;match openssl_ed25519::verify(pubkey.as_ref().unwrap(),&p.signature,&msg){Ok(true)=>r.set("cryptographic_validity","VALID"),Ok(false)=>{r.set("cryptographic_validity","INVALID");r.err("SIGNATURE_INVALID")},Err(_)=>{r.set("cryptographic_validity","NOT_EVALUATED");r.err("VERIFICATION_METHOD_MALFORMED")}}}
 if !understood_purpose.contains(&p.purpose){r.set("purpose_status","UNSUPPORTED");r.err("UNSUPPORTED_PROOF_PURPOSE")}else if let Some(Json::String(exp))=context.get("expected_purpose"){if exp==&p.purpose{r.set("purpose_status","MATCH")}else{r.set("purpose_status","MISMATCH");r.err("PURPOSE_MISMATCH")}}else{r.set("purpose_status","UNDERSTOOD")}
 if let Some(Json::String(exp))=context.get("expected_domain"){match &p.domain{None=>{r.set("domain_status","MISMATCH");r.err("DOMAIN_REQUIRED")},Some(v)if v==exp=>r.set("domain_status","MATCH"),Some(_)=>{r.set("domain_status","MISMATCH");r.err("DOMAIN_MISMATCH")}}}
 if let Some(Json::String(exphex))=context.get("expected_challenge_hex"){let exp=hex_decode(exphex).map_err(|e|OlpError::malformed("MALFORMED_INPUT",e))?;match &p.challenge{None=>{r.set("challenge_status","MISMATCH");r.err("CHALLENGE_REQUIRED")},Some(v)if v==&exp=>r.set("challenge_status","MATCH"),Some(_)=>{r.set("challenge_status","MISMATCH");r.err("CHALLENGE_MISMATCH")}}}
 if let Some(Json::String(eval))=context.get("evaluation_time"){let t=time::parse(eval).ok_or_else(||OlpError::malformed("MALFORMED_INPUT","invalid evaluation_time"))?;if let Some(ex)=&p.expires{let et=time::parse(ex).unwrap();if t>et{r.set("temporal_status","EXPIRED");r.err("PROOF_EXPIRED")}else{r.set("temporal_status","CURRENT")}}else{r.set("temporal_status","CURRENT")}}
 if let Some(Json::String(status))=context.get("verification_method_status"){r.set("verification_method_status",status);match status.as_str(){"RETIRED"=>r.warn("VERIFICATION_METHOD_RETIRED"),"EXPIRED"=>r.warn("VERIFICATION_METHOD_EXPIRED"),"SUSPENDED"=>r.warn("VERIFICATION_METHOD_SUSPENDED"),"REVOKED"=>r.warn("VERIFICATION_METHOD_REVOKED"),"COMPROMISED"=>r.warn("VERIFICATION_METHOD_COMPROMISED"),"UNKNOWN"=>r.warn("VERIFICATION_METHOD_STATUS_UNKNOWN"),_=>{}}}
 Ok(r.finish())}
