fn resolve_evidence(req:&Request,sources:&[Json])->Result<Json,OlpError>{
    let target=parse_evidence_ref(&req.target)?; let mut candidates_seen=0usize; let mut mismatches=Vec::new(); let mut freshness_blocked=false;
    for (source_index,sv) in sources.iter().enumerate(){let s=sv.as_object().map_err(|e|malformed("RESOLVER_RESPONSE_MALFORMED",e))?;let class=match s.get("source_class"){Some(Json::String(x))=>x.as_str(),_=>continue};if class!="bundle"&&class!="localStore"{continue;}let sid=match s.get("source_identifier"){Some(Json::String(x))=>Some(x.clone()),None|Some(Json::Null)=>None,_=>return Err(malformed("RESOLVER_RESPONSE_MALFORMED","source identifier must be text or null"))};let candidates=match s.get("candidates"){None=>&[][..],Some(v)=>v.as_array().map_err(|e|malformed("RESOLVER_RESPONSE_MALFORMED",e))?};
        for cv in candidates{candidates_seen+=1;if candidates_seen>10_000{return Ok(Json::Object(base("LIMIT_EXCEEDED",vec!["RESOLUTION_LIMIT_EXCEEDED"],vec![],0,"NOT_APPLICABLE")));}let c=cv.as_object().map_err(|e|malformed("RESOLVER_RESPONSE_MALFORMED",e))?;let lookup=parse_evidence_ref(c.get("lookup_ref").ok_or_else(||malformed("RESOLVER_RESPONSE_MALFORMED","missing lookup_ref"))?)?;if lookup!=target{continue;}if let Some(v)=c.get("size_bytes"){let n=v.as_u64().map_err(|e|malformed("RESOLVER_RESPONSE_MALFORMED",e))?;if size_exceeds(req,n){return Ok(Json::Object(base("LIMIT_EXCEEDED",vec!["RESOLUTION_LIMIT_EXCEEDED"],vec![],0,"NOT_APPLICABLE")));}}
            let digest=if target.kind==0{let rec=c.get("record").ok_or_else(||malformed("RESOLVER_RESPONSE_MALFORMED","candidate record missing"))?;record::identity_digest(rec)?}else{let p=c.get("proof").ok_or_else(||malformed("RESOLVER_RESPONSE_MALFORMED","candidate proof missing"))?;proof_identity::proof_identity_digest_for(p)?};let actual=EvidenceRef{kind:target.kind,digest};if actual!=target{let mut m=Json::object();m.insert("requested".into(),ref_json(&target));m.insert("actual".into(),ref_json(&actual));m.insert("source_index".into(),Json::Int(source_index as i128));mismatches.push(Json::Object(m));continue;}
            let freshness=source_freshness(s)?;if req.require_fresh&&freshness!="FRESH"{freshness_blocked=true;continue;}let mut out=base("RESOLVED",vec![],vec![],0,&freshness);let mut ma=Json::object();ma.insert("ref".into(),ref_json(&target));ma.insert("source_class".into(),Json::String(class.into()));ma.insert("source_identifier".into(),sid.clone().map(Json::String).unwrap_or(Json::Null));out.insert("matches".into(),Json::Array(vec![Json::Object(ma)]));let mut pr=Json::object();pr.insert("source_class".into(),Json::String(class.into()));pr.insert("source_identifier".into(),sid.map(Json::String).unwrap_or(Json::Null));pr.insert("source_index".into(),Json::Int(source_index as i128));out.insert("provenance".into(),Json::Array(vec![Json::Object(pr)]));out.insert("conflicts".into(),Json::Array(mismatches));return Ok(Json::Object(out));
        }
    }
    if freshness_blocked{let mut out=base("POLICY_BLOCKED",vec!["FRESHNESS_REQUIREMENT_NOT_MET"],vec![],0,"NOT_APPLICABLE");out.insert("conflicts".into(),Json::Array(mismatches));return Ok(Json::Object(out));}
    if !mismatches.is_empty(){let mut out=base("IDENTITY_MISMATCH",vec!["RESOLVED_IDENTITY_MISMATCH"],vec![],0,"NOT_APPLICABLE");out.insert("conflicts".into(),Json::Array(mismatches));return Ok(Json::Object(out));}
    Ok(Json::Object(base("NOT_FOUND",vec!["RESOLUTION_NOT_FOUND"],vec![],0,"NOT_APPLICABLE")))
}

