//! Independent Specification 0012 deterministic transport-encoding core.
//! No sockets, HTTP, DNS, authorization, redirects, caching, or ambient I/O.
use std::collections::{BTreeMap,BTreeSet};
use crate::{error::OlpError,json::Json,proof_identity,record,util::{base64url_no_pad,hex_decode,hex_encode,is_absolute_uri}};

const SAFE_JSON_INT:i128=(1i128<<53)-1;
const RECORD_INT_MIN:i128=-(1i128<<64);
const RECORD_INT_MAX:i128=(1i128<<64)-1;
const MAX_DEPTH:usize=64;
const MAX_ITEMS:usize=100_000;
const MAX_BYTES:usize=16*1024*1024;
const CORE_TYPES:[&str;11]=["record","proof","bundle","bundleQuery","resolutionRequest","resolutionResult","disclosureRequest","disclosureResult","capabilities","submissionResult","error"];

#[derive(Clone,Debug,PartialEq,Eq)]
enum AValue{Null,Bool(bool),Int(i128),Bytes(Vec<u8>),Text(String),Array(Vec<AValue>),Map(Vec<(AValue,AValue)>)}

fn malformed(reason:&str,msg:impl Into<String>)->OlpError{OlpError::malformed(reason,msg)}
fn unsupported(reason:&str,msg:impl Into<String>)->OlpError{OlpError::unsupported(reason,msg)}

fn b64_value(c:u8)->Option<u8>{match c{b'A'..=b'Z'=>Some(c-b'A'),b'a'..=b'z'=>Some(c-b'a'+26),b'0'..=b'9'=>Some(c-b'0'+52),b'-'=>Some(62),b'_'=>Some(63),_=>None}}
fn base64url_decode_canonical(s:&str,expected:Option<usize>,reason:&str)->Result<Vec<u8>,OlpError>{
 let b=s.as_bytes();if b.iter().any(|c|b64_value(*c).is_none())||b.len()%4==1{return Err(malformed(reason,"invalid unpadded base64url"));}
 let mut out=Vec::with_capacity(b.len()*3/4);let mut i=0;
 while i+4<=b.len(){let a=b64_value(b[i]).unwrap()as u32;let c=b64_value(b[i+1]).unwrap()as u32;let d=b64_value(b[i+2]).unwrap()as u32;let e=b64_value(b[i+3]).unwrap()as u32;let n=(a<<18)|(c<<12)|(d<<6)|e;out.extend_from_slice(&[((n>>16)&255)as u8,((n>>8)&255)as u8,(n&255)as u8]);i+=4;}
 match b.len()-i{0=>{},2=>{let a=b64_value(b[i]).unwrap();let c=b64_value(b[i+1]).unwrap();if c&0x0f!=0{return Err(malformed(reason,"non-canonical base64url pad bits"));}out.push((a<<2)|(c>>4));},3=>{let a=b64_value(b[i]).unwrap();let c=b64_value(b[i+1]).unwrap();let d=b64_value(b[i+2]).unwrap();if d&0x03!=0{return Err(malformed(reason,"non-canonical base64url pad bits"));}out.push((a<<2)|(c>>4));out.push((c<<4)|(d>>2));},_=>return Err(malformed(reason,"invalid base64url length"))}
 if expected.is_some_and(|n|out.len()!=n){return Err(malformed(reason,"decoded value has wrong length"));}
 if base64url_no_pad(&out)!=s{return Err(malformed(reason,"base64url value is not canonical"));}Ok(out)
}

fn identity_prefix(kind:&str)->Result<&'static str,OlpError>{match kind{"record"=>Ok("r1_"),"proof"=>Ok("p1_"),"bundle"=>Ok("b1_"),_=>Err(unsupported("UNSUPPORTED_IDENTITY_KIND","unsupported textual identity kind"))}}
fn encode_identity(kind:&str,digest:&[u8])->Result<String,OlpError>{if digest.len()!=32{return Err(malformed("MALFORMED_IDENTITY_TEXT","identity digest must contain 32 octets"));}Ok(format!("{}{}",identity_prefix(kind)?,base64url_no_pad(digest)))}
fn decode_identity(text:&str,expected:Option<&str>)->Result<(&'static str,Vec<u8>),OlpError>{
 if text.len()!=46{return Err(malformed("MALFORMED_IDENTITY_TEXT","textual identity length is invalid"));}
 let (kind,prefix)=if text.starts_with("r1_"){("record","r1_")}else if text.starts_with("p1_"){("proof","p1_")}else if text.starts_with("b1_"){("bundle","b1_")}else{return Err(malformed("MALFORMED_IDENTITY_TEXT","invalid textual identity prefix"));};
 if let Some(want)=expected{identity_prefix(want)?;if want!=kind{return Err(malformed("IDENTITY_TEXT_KIND_MISMATCH","identity prefix does not match context"));}}
 let digest=base64url_decode_canonical(&text[prefix.len()..],Some(32),"MALFORMED_IDENTITY_TEXT")?;Ok((kind,digest))
}

fn token(v:&AValue)->String{match v{AValue::Null=>"n".into(),AValue::Bool(x)=>format!("b:{x}"),AValue::Int(x)=>format!("i:{x}"),AValue::Bytes(x)=>format!("y:{}",hex_encode(x)),AValue::Text(x)=>format!("t:{}:{x}",x.len()),AValue::Array(a)=>format!("a:[{}]",a.iter().map(token).collect::<Vec<_>>().join(",")),AValue::Map(m)=>{let mut p=m.iter().map(|(k,v)|(token(k),token(v))).collect::<Vec<_>>();p.sort();format!("m:{{{}}}",p.into_iter().map(|(k,v)|format!("{k}={v}")).collect::<Vec<_>>().join(","))}}}
fn validate_unique(entries:&[(AValue,AValue)])->Result<(),OlpError>{let mut s=BTreeSet::new();for(k,_)in entries{if !s.insert(token(k)){return Err(malformed("DUPLICATE_OJVE_MAP_KEY","duplicate abstract OJVE map key"));}}Ok(())}
fn from_projection(v:&Json,depth:usize)->Result<AValue,OlpError>{
 if depth>MAX_DEPTH{return Err(malformed("MALFORMED_TRANSPORT_INPUT","transport value depth exceeds limit"));}
 match v{Json::Null=>Ok(AValue::Null),Json::Bool(x)=>Ok(AValue::Bool(*x)),Json::Int(x)=>Ok(AValue::Int(*x)),Json::String(s)=>Ok(AValue::Text(s.clone())),Json::Array(a)=>{if a.len()>MAX_ITEMS{return Err(malformed("MALFORMED_TRANSPORT_INPUT","array exceeds item limit"));}Ok(AValue::Array(a.iter().map(|x|from_projection(x,depth+1)).collect::<Result<_,_>>()?))},Json::Object(m) if m.len()==1&&m.contains_key("$bytes")=>{let h=m.get("$bytes").unwrap().as_str().map_err(|e|malformed("MALFORMED_TRANSPORT_INPUT",e))?;let b=hex_decode(h).map_err(|e|malformed("MALFORMED_TRANSPORT_INPUT",e))?;if b.len()>MAX_BYTES{return Err(malformed("MALFORMED_TRANSPORT_INPUT","byte string exceeds limit"));}Ok(AValue::Bytes(b))},Json::Object(m) if m.len()==1&&m.contains_key("$map")=>{let a=m.get("$map").unwrap().as_array().map_err(|e|malformed("MALFORMED_TRANSPORT_INPUT",e))?;if a.len()>MAX_ITEMS{return Err(malformed("MALFORMED_TRANSPORT_INPUT","map exceeds item limit"));}let mut out=Vec::new();for e in a{let p=e.as_array().map_err(|_|malformed("MALFORMED_TRANSPORT_INPUT","$map entry must be pair"))?;if p.len()!=2{return Err(malformed("MALFORMED_TRANSPORT_INPUT","$map entry must have two elements"));}out.push((from_projection(&p[0],depth+1)?,from_projection(&p[1],depth+1)?));}validate_unique(&out)?;Ok(AValue::Map(out))},Json::Object(m)=>{let mut out=Vec::new();for(k,x)in m{out.push((AValue::Text(k.clone()),from_projection(x,depth+1)?));}validate_unique(&out)?;Ok(AValue::Map(out))}}
}
fn project(v:&AValue)->Json{match v{AValue::Null=>Json::Null,AValue::Bool(x)=>Json::Bool(*x),AValue::Int(x)=>Json::Int(*x),AValue::Bytes(b)=>{let mut m=Json::object();m.insert("$bytes".into(),Json::String(hex_encode(b)));Json::Object(m)},AValue::Text(s)=>Json::String(s.clone()),AValue::Array(a)=>Json::Array(a.iter().map(project).collect()),AValue::Map(entries)=>{let mut m=Json::object();m.insert("$map".into(),Json::Array(entries.iter().map(|(k,v)|Json::Array(vec![project(k),project(v)])).collect()));Json::Object(m)}}}

fn encode_ojve(v:&AValue,depth:usize)->Result<Json,OlpError>{
 if depth>MAX_DEPTH{return Err(malformed("MALFORMED_OJVE","OJVE depth exceeds limit"));}
 match v{AValue::Null=>Ok(Json::Null),AValue::Bool(x)=>Ok(Json::Bool(*x)),AValue::Int(x)=>{if *x<RECORD_INT_MIN||*x>RECORD_INT_MAX{return Err(malformed("MALFORMED_OJVE","integer outside OLP v1 range"));}if x.abs()<=SAFE_JSON_INT{Ok(Json::Int(*x))}else{let mut m=Json::object();m.insert("$olp".into(),Json::String("int".into()));m.insert("v".into(),Json::String(x.to_string()));Ok(Json::Object(m))}},AValue::Bytes(b)=>{if b.len()>MAX_BYTES{return Err(malformed("MALFORMED_OJVE","byte string exceeds limit"));}let mut m=Json::object();m.insert("$olp".into(),Json::String("bytes".into()));m.insert("v".into(),Json::String(base64url_no_pad(b)));Ok(Json::Object(m))},AValue::Text(s)=>Ok(Json::String(s.clone())),AValue::Array(a)=>{if a.len()>MAX_ITEMS{return Err(malformed("MALFORMED_OJVE","array exceeds item limit"));}Ok(Json::Array(a.iter().map(|x|encode_ojve(x,depth+1)).collect::<Result<_,_>>()?))},AValue::Map(entries)=>{validate_unique(entries)?;if entries.len()>MAX_ITEMS{return Err(malformed("MALFORMED_OJVE","map exceeds item limit"));}let mut m=Json::object();m.insert("$olp".into(),Json::String("map".into()));m.insert("v".into(),Json::Array(entries.iter().map(|(k,v)|Ok(Json::Array(vec![encode_ojve(k,depth+1)?,encode_ojve(v,depth+1)?]))).collect::<Result<_,OlpError>>()?));Ok(Json::Object(m))}}
}
fn canonical_decimal(s:&str)->bool{if s=="0"{return true;}let b=s.as_bytes();let start=if b.first()==Some(&b'-'){if b.len()<2||b[1]==b'0'{return false;}1}else{if b.first()==Some(&b'0'){return false;}0};b[start..].iter().all(|c|c.is_ascii_digit())}
fn decode_ojve(v:&Json,depth:usize)->Result<AValue,OlpError>{
 if depth>MAX_DEPTH{return Err(malformed("MALFORMED_OJVE","OJVE depth exceeds limit"));}
 match v{Json::Null=>Ok(AValue::Null),Json::Bool(x)=>Ok(AValue::Bool(*x)),Json::Int(x)=>{if x.abs()>SAFE_JSON_INT{return Err(malformed("MALFORMED_OJVE","unsafe JSON integer must use wrapper"));}Ok(AValue::Int(*x))},Json::String(s)=>Ok(AValue::Text(s.clone())),Json::Array(a)=>Ok(AValue::Array(a.iter().map(|x|decode_ojve(x,depth+1)).collect::<Result<_,_>>()?)),Json::Object(m)=>{let Some(tagv)=m.get("$olp")else{return Err(malformed("MALFORMED_OJVE","OJVE maps require explicit wrapper"));};let tag=tagv.as_str().map_err(|_|malformed("MALFORMED_OJVE","OJVE tag must be text"))?;if !matches!(tag,"int"|"bytes"|"map"){return Err(unsupported("UNSUPPORTED_OJVE_TAG","unsupported OJVE tag"));}if m.len()!=2||!m.contains_key("v"){return Err(malformed("MALFORMED_OJVE","OJVE wrapper shape invalid"));}let raw=m.get("v").unwrap();match tag{"int"=>{let s=raw.as_str().map_err(|_|malformed("MALFORMED_OJVE","integer wrapper must contain text"))?;if !canonical_decimal(s){return Err(malformed("MALFORMED_OJVE","integer decimal not canonical"));}let n=s.parse::<i128>().map_err(|_|malformed("MALFORMED_OJVE","integer outside supported range"))?;if n<RECORD_INT_MIN||n>RECORD_INT_MAX{return Err(malformed("MALFORMED_OJVE","integer outside OLP v1 range"));}Ok(AValue::Int(n))},"bytes"=>{let s=raw.as_str().map_err(|_|malformed("MALFORMED_OJVE","byte wrapper must contain text"))?;let b=base64url_decode_canonical(s,None,"MALFORMED_OJVE")?;if b.len()>MAX_BYTES{return Err(malformed("MALFORMED_OJVE","byte string exceeds limit"));}Ok(AValue::Bytes(b))},"map"=>{let a=raw.as_array().map_err(|_|malformed("MALFORMED_OJVE","map v must be array"))?;let mut out=Vec::new();for e in a{let p=e.as_array().map_err(|_|malformed("MALFORMED_OJVE","map entry must be pair"))?;if p.len()!=2{return Err(malformed("MALFORMED_OJVE","map entry must have two elements"));}out.push((decode_ojve(&p[0],depth+1)?,decode_ojve(&p[1],depth+1)?));}validate_unique(&out)?;Ok(AValue::Map(out))},_=>unreachable!()}}}
}

fn valid_message_type(s:&str)->bool{CORE_TYPES.contains(&s)||is_absolute_uri(s)}
fn envelope_json(message_type:&str,payload:&AValue)->Result<Json,OlpError>{if !valid_message_type(message_type){return Err(malformed("MALFORMED_TRANSPORT_ENVELOPE","invalid transport message type"));}let mut m=Json::object();m.insert("olp".into(),Json::Int(1));m.insert("type".into(),Json::String(message_type.into()));m.insert("payload".into(),encode_ojve(payload,0)?);Ok(Json::Object(m))}
fn decode_envelope(j:&Json)->Result<(String,AValue),OlpError>{let m=j.as_object().map_err(|e|malformed("MALFORMED_TRANSPORT_ENVELOPE",e))?;if m.len()!=3||!m.contains_key("olp")||!m.contains_key("type")||!m.contains_key("payload"){return Err(malformed("MALFORMED_TRANSPORT_ENVELOPE","invalid transport envelope shape"));}let ver=m.get("olp").unwrap().as_i64().map_err(|e|malformed("MALFORMED_TRANSPORT_ENVELOPE",e))?;if ver!=1{return Err(unsupported("UNSUPPORTED_TRANSPORT_ENVELOPE_VERSION","unsupported transport version"));}let typ=m.get("type").unwrap().as_str().map_err(|e|malformed("MALFORMED_TRANSPORT_ENVELOPE",e))?;if !valid_message_type(typ){return Err(malformed("MALFORMED_TRANSPORT_ENVELOPE","invalid transport message type"));}Ok((typ.into(),decode_ojve(m.get("payload").unwrap(),0)?))}

fn as_text_map(v:&AValue)->Result<BTreeMap<String,AValue>,OlpError>{let AValue::Map(entries)=v else{return Err(malformed("MALFORMED_TRANSPORT_INPUT","expected map"));};let mut out=BTreeMap::new();for(k,v)in entries{let AValue::Text(s)=k else{return Err(malformed("TRANSPORT_OBJECT_KEY_TYPE_MISMATCH","target object requires text keys"));};if out.insert(s.clone(),v.clone()).is_some(){return Err(malformed("TRANSPORT_OBJECT_KEY_COLLISION","duplicate object key"));}}Ok(out)}
fn materialize_text_json(v:&AValue)->Result<Json,OlpError>{match v{AValue::Null=>Ok(Json::Null),AValue::Bool(x)=>Ok(Json::Bool(*x)),AValue::Int(x)=>Ok(Json::Int(*x)),AValue::Bytes(_)=>Err(malformed("TRANSPORT_OBJECT_KEY_TYPE_MISMATCH","raw byte value cannot be materialized as ordinary JSON object representation")),AValue::Text(s)=>Ok(Json::String(s.clone())),AValue::Array(a)=>Ok(Json::Array(a.iter().map(materialize_text_json).collect::<Result<_,_>>()?)),AValue::Map(entries)=>{let mut m=Json::object();for(k,v)in entries{let AValue::Text(s)=k else{return Err(malformed("TRANSPORT_OBJECT_KEY_TYPE_MISMATCH","target object requires text keys"));};if m.insert(s.clone(),materialize_text_json(v)?).is_some(){return Err(malformed("TRANSPORT_OBJECT_KEY_COLLISION","duplicate object key"));}}Ok(Json::Object(m))}}}
fn materialize_record(v:&AValue)->Result<Json,OlpError>{materialize_text_json(v)}

fn proof_to_abstract(p:&Json)->Result<AValue,OlpError>{let o=p.as_object().map_err(|e|malformed("MALFORMED_TRANSPORT_INPUT",e))?;let mut e=Vec::new();for key in ["type","version","cryptosuite","proofPurpose","verificationMethod"]{let v=o.get(key).ok_or_else(||malformed("MALFORMED_TRANSPORT_INPUT",format!("missing proof {key}")))?;e.push((AValue::Text(key.into()),from_projection(v,1)?));}let rc=o.get("recordCommitment").ok_or_else(||malformed("MALFORMED_TRANSPORT_INPUT","missing recordCommitment"))?.as_object().map_err(|e|malformed("MALFORMED_TRANSPORT_INPUT",e))?;let alg=rc.get("algorithm").ok_or_else(||malformed("MALFORMED_TRANSPORT_INPUT","missing algorithm"))?.as_i64().map_err(|e|malformed("MALFORMED_TRANSPORT_INPUT",e))?;let dh=rc.get("digest_hex").ok_or_else(||malformed("MALFORMED_TRANSPORT_INPUT","missing digest"))?.as_str().map_err(|e|malformed("MALFORMED_TRANSPORT_INPUT",e))?;let digest=hex_decode(dh).map_err(|e|malformed("MALFORMED_TRANSPORT_INPUT",e))?;e.push((AValue::Text("recordCommitment".into()),AValue::Array(vec![AValue::Int(alg as i128),AValue::Bytes(digest)])));let sig=hex_decode(o.get("proofValue_hex").ok_or_else(||malformed("MALFORMED_TRANSPORT_INPUT","missing proofValue"))?.as_str().map_err(|e|malformed("MALFORMED_TRANSPORT_INPUT",e))?).map_err(|e|malformed("MALFORMED_TRANSPORT_INPUT",e))?;e.push((AValue::Text("proofValue".into()),AValue::Bytes(sig)));for key in ["created","expires","domain"]{if let Some(v)=o.get(key){e.push((AValue::Text(key.into()),from_projection(v,1)?));}}for(key,outkey)in [("challenge_hex","challenge"),("nonce_hex","nonce")]{if let Some(v)=o.get(key){let b=hex_decode(v.as_str().map_err(|e|malformed("MALFORMED_TRANSPORT_INPUT",e))?).map_err(|e|malformed("MALFORMED_TRANSPORT_INPUT",e))?;e.push((AValue::Text(outkey.into()),AValue::Bytes(b)));}}e.push((AValue::Text("critical".into()),from_projection(o.get("critical").unwrap_or(&Json::Array(Vec::new())),1)?));e.push((AValue::Text("extensions".into()),from_projection(o.get("extensions").unwrap_or(&Json::Object(BTreeMap::new())),1)?));Ok(AValue::Map(e))}
fn proof_from_abstract(v:&AValue)->Result<Json,OlpError>{let m=as_text_map(v)?;let mut o=Json::object();for key in ["type","version","cryptosuite","proofPurpose","verificationMethod"]{let x=m.get(key).ok_or_else(||malformed("MALFORMED_TRANSPORT_INPUT",format!("missing proof {key}")))?;o.insert(key.into(),project(x));}let rc=m.get("recordCommitment").ok_or_else(||malformed("MALFORMED_TRANSPORT_INPUT","missing recordCommitment"))?;let AValue::Array(a)=rc else{return Err(malformed("MALFORMED_TRANSPORT_INPUT","recordCommitment must be array"));};if a.len()!=2{return Err(malformed("MALFORMED_TRANSPORT_INPUT","recordCommitment must have two elements"));}let AValue::Int(alg)=a[0] else{return Err(malformed("MALFORMED_TRANSPORT_INPUT","algorithm must be integer"));};let AValue::Bytes(ref digest)=a[1] else{return Err(malformed("MALFORMED_TRANSPORT_INPUT","digest must be bytes"));};let mut r=Json::object();r.insert("algorithm".into(),Json::Int(alg));r.insert("digest_hex".into(),Json::String(hex_encode(digest)));o.insert("recordCommitment".into(),Json::Object(r));let AValue::Bytes(sig)=m.get("proofValue").ok_or_else(||malformed("MALFORMED_TRANSPORT_INPUT","missing proofValue"))? else{return Err(malformed("MALFORMED_TRANSPORT_INPUT","proofValue must be bytes"));};o.insert("proofValue_hex".into(),Json::String(hex_encode(sig)));for key in ["created","expires","domain"]{if let Some(x)=m.get(key){o.insert(key.into(),project(x));}}for(key,outkey)in [("challenge","challenge_hex"),("nonce","nonce_hex")]{if let Some(AValue::Bytes(b))=m.get(key){o.insert(outkey.into(),Json::String(hex_encode(b)));}}o.insert("critical".into(),project(m.get("critical").unwrap_or(&AValue::Array(Vec::new()))));o.insert("extensions".into(),project(m.get("extensions").unwrap_or(&AValue::Map(Vec::new()))));Ok(Json::Object(o))}

pub fn operation(name:&str,input:&Json)->Result<Json,OlpError>{match name{
 "encode_identity_text"=>{let kind=input.get("kind").map_err(|e|malformed("MALFORMED_INPUT",e))?.as_str().map_err(|e|malformed("MALFORMED_INPUT",e))?;let d=hex_decode(input.get("digest_hex").map_err(|e|malformed("MALFORMED_INPUT",e))?.as_str().map_err(|e|malformed("MALFORMED_INPUT",e))?).map_err(|e|malformed("MALFORMED_INPUT",e))?;let mut o=Json::object();o.insert("text".into(),Json::String(encode_identity(kind,&d)?));Ok(Json::Object(o))},
 "decode_identity_text"=>{let text=input.get("text").map_err(|e|malformed("MALFORMED_INPUT",e))?.as_str().map_err(|e|malformed("MALFORMED_INPUT",e))?;let expected=input.get_opt("expected_kind").map_err(|e|malformed("MALFORMED_INPUT",e))?.map(|v|v.as_str()).transpose().map_err(|e|malformed("MALFORMED_INPUT",e))?;let(k,d)=decode_identity(text,expected)?;let mut o=Json::object();o.insert("kind".into(),Json::String(k.into()));o.insert("digest_hex".into(),Json::String(hex_encode(&d)));Ok(Json::Object(o))},
 "encode_ojve"=>{let v=from_projection(input.get("value").map_err(|e|malformed("MALFORMED_INPUT",e))?,0)?;let mut o=Json::object();o.insert("ojve".into(),encode_ojve(&v,0)?);Ok(Json::Object(o))},
 "decode_ojve"=>{let v=decode_ojve(input.get("ojve").map_err(|e|malformed("MALFORMED_INPUT",e))?,0)?;let mut o=Json::object();o.insert("value".into(),project(&v));Ok(Json::Object(o))},
 "encode_transport_envelope"=>{let typ=input.get("message_type").map_err(|e|malformed("MALFORMED_INPUT",e))?.as_str().map_err(|e|malformed("MALFORMED_INPUT",e))?;let p=from_projection(input.get("payload").map_err(|e|malformed("MALFORMED_INPUT",e))?,0)?;let mut o=Json::object();o.insert("json".into(),envelope_json(typ,&p)?);Ok(Json::Object(o))},
 "decode_transport_envelope"=>{let(typ,p)=decode_envelope(input.get("json").map_err(|e|malformed("MALFORMED_INPUT",e))?)?;let mut o=Json::object();o.insert("message_type".into(),Json::String(typ));o.insert("payload".into(),project(&p));Ok(Json::Object(o))},
 "transport_record_equivalence"=>{let r=input.get("record").map_err(|e|malformed("MALFORMED_INPUT",e))?;let before=record::identity_digest(r)?;let a=from_projection(r,0)?;let wire=encode_ojve(&a,0)?;let back=decode_ojve(&wire,0)?;let reconstructed=materialize_record(&back)?;let after=record::identity_digest(&reconstructed)?;let mut o=Json::object();o.insert("record_identity_before_hex".into(),Json::String(hex_encode(&before)));o.insert("record_identity_after_json_hex".into(),Json::String(hex_encode(&after)));o.insert("identity_preserved".into(),Json::Bool(before==after));Ok(Json::Object(o))},
 "transport_proof_equivalence"=>{let p=input.get("proof").map_err(|e|malformed("MALFORMED_INPUT",e))?;let before=proof_identity::proof_identity_digest_for(p)?;let a=proof_to_abstract(p)?;let wire=encode_ojve(&a,0)?;let back=decode_ojve(&wire,0)?;let reconstructed=proof_from_abstract(&back)?;let after=proof_identity::proof_identity_digest_for(&reconstructed)?;let original_sig=p.get("proofValue_hex").map_err(|e|malformed("MALFORMED_INPUT",e))?.as_str().map_err(|e|malformed("MALFORMED_INPUT",e))?;let new_sig=reconstructed.get("proofValue_hex").map_err(|e|malformed("MALFORMED_INPUT",e))?.as_str().map_err(|e|malformed("MALFORMED_INPUT",e))?;let mut o=Json::object();o.insert("proof_identity_before_hex".into(),Json::String(hex_encode(&before)));o.insert("proof_identity_after_json_hex".into(),Json::String(hex_encode(&after)));o.insert("identity_preserved".into(),Json::Bool(before==after));o.insert("proof_value_preserved".into(),Json::Bool(original_sig==new_sig));Ok(Json::Object(o))},
 _=>Err(unsupported("UNSUPPORTED_OPERATION",name))
}}

#[cfg(test)]mod tests{use super::*;#[test]fn rejects_noncanonical_pad_bits(){let s=format!("r1_{}","A".repeat(42)+"B");assert!(decode_identity(&s,None).is_err());}#[test]fn map_key_types_stay_distinct(){let m=AValue::Map(vec![(AValue::Int(1),AValue::Text("i".into())),(AValue::Text("1".into()),AValue::Text("t".into())),(AValue::Bytes(vec![49]),AValue::Text("b".into()))]);assert_eq!(decode_ojve(&encode_ojve(&m,0).unwrap(),0).unwrap(),m);}}
